const platforms = ['X','小红书','抖音','快手','微信公众号','西瓜视频','知乎','掘金'];
let state = { contents: [], accounts: [], jobs: [] };
let activeFilter = 'all';
let selectedPublishPlatforms = [];
const $ = (s) => document.querySelector(s);

async function boot() { state = await window.autopost.getState(); state.settings ||= { cacheRoot: '' }; $('#cache-root').value = state.settings.cacheRoot || ''; render(); }
function save() { return window.autopost.saveState(state); }
function render() { $('#content-total').textContent = state.contents.length; $('#all-count').textContent = state.contents.length; $('#queue-count').textContent = state.jobs.length; $('#queue-pill').textContent = `${state.jobs.length} 个任务`; renderContents(); renderQueue(); renderAccounts(); }
function renderContents() {
  const query = ($('#search')?.value || '').toLowerCase();
  const list = state.contents.filter(c => (activeFilter === 'all' || c.type === activeFilter || (activeFilter === 'template' && c.template)) && (!query || `${c.title} ${c.tags}`.toLowerCase().includes(query)));
  $('#content-grid').innerHTML = list.map(c => `<article class="content-card"><div class="card-visual ${c.type === 'article' ? 'article' : ''}"><span class="type-chip">${c.type === 'video' ? 'VIDEO' : 'ARTICLE'}${c.template ? ' · TEMPLATE' : ''}</span></div><div class="card-body"><h3 class="card-title">${escapeHtml(c.title)}</h3><div class="card-meta"><span>${c.platforms.length} 个发布目标</span><span>${new Date(c.createdAt).toLocaleDateString('zh-CN')}</span></div><div class="card-tags">${escapeHtml(c.tags || '未添加标签')}</div></div></article>`).join('');
  $('#empty-state').style.display = list.length ? 'none' : 'block';
}
function renderQueue() { $('#queue-list').innerHTML = state.jobs.length ? state.jobs.map((j,i) => { const targetNames = (j.targets || []).map(t => { const account = state.accounts.find(a => a.id === t.accountId); return `${t.platform} / ${account?.name || '账号'}`; }); return `<div class="queue-item"><span class="queue-index">0${i+1}</span><strong class="queue-title">${escapeHtml(j.title)}</strong><span class="queue-platforms">${escapeHtml(targetNames.join(' · ') || j.platforms.join(' · '))}</span><span class="status ${j.status}">${j.status === 'ready' ? '待发布' : '草稿'}</span></div>`; }).join('') : '<div class="empty-state"><div class="empty-icon">◷</div><h3>还没有发布任务</h3><p>从内容库新建内容后，选择平台即可加入队列。</p></div>'; }
function renderAccounts() { $('#account-grid').innerHTML = state.accounts.map(a => `<div class="account-row ${state.activeAccountId === a.id ? 'account-active' : ''}"><div class="list-platform"><span class="platform-logo">${a.platform.slice(0,1)}</span><strong>${a.platform}</strong></div><div class="list-account"><strong>${escapeHtml(a.name)}</strong><small>${a.status}</small></div><div class="list-note">${escapeHtml(a.note || '—')}</div><div><span class="proxy-badge ${a.proxy?.enabled ? 'on' : ''}">${a.proxy?.enabled ? '已配置' : '直连'}</span></div><div class="list-cache" title="${escapeHtml(a.cacheDir || '使用应用默认隔离目录')}">${escapeHtml(a.cacheDir || '默认隔离目录')}</div><div class="account-actions"><button class="login-account" data-account-id="${a.id}">登录</button><button class="check-account" data-account-id="${a.id}">检测</button><button class="folder-button open-account" data-account-id="${a.id}" title="打开缓存目录">↗</button><button class="folder-button choose-account" data-account-id="${a.id}" title="选择缓存目录">⌂</button></div></div>`).join(''); }
function escapeHtml(value='') { return value.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function renderAccountPicker() { const accounts = state.accounts.filter(a => selectedPublishPlatforms.includes(a.platform)); $('#account-picker').innerHTML = accounts.length ? selectedPublishPlatforms.map(platform => { const matches = accounts.filter(a => a.platform === platform); return `<div class="account-group"><strong>${platform}</strong><div>${matches.map(a => `<label class="account-option"><input type="checkbox" data-target-platform="${platform}" data-account-id="${a.id}"><span>${escapeHtml(a.name)}${a.note ? ` · ${escapeHtml(a.note)}` : ''}</span></label>`).join('')}</div></div>`; }).join('') : '<p class="form-hint">先选择平台，再为每个平台选择账号。</p>'; }
function openModal() { $('#modal').classList.remove('hidden'); selectedPublishPlatforms = []; $('#platform-picker').innerHTML = platforms.map(p => `<button type="button" class="platform-option" data-platform="${p}">${p}</button>`).join(''); renderAccountPicker(); }
function closeModal() { $('#modal').classList.add('hidden'); $('#content-form').reset(); }
document.querySelectorAll('.nav-item').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach(b => b.classList.remove('active')); btn.classList.add('active'); document.querySelectorAll('.view').forEach(v => v.classList.add('hidden')); $(`#${btn.dataset.view}-view`).classList.remove('hidden'); $('#page-title').textContent = btn.textContent.trim().replace(/\d+$/, ''); }));
document.querySelectorAll('.tab').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(b => b.classList.remove('active')); btn.classList.add('active'); activeFilter = btn.dataset.filter; renderContents(); }));
$('#new-content').addEventListener('click', openModal); $('#empty-new').addEventListener('click', openModal); $('#close-modal').addEventListener('click', closeModal); $('#cancel-modal').addEventListener('click', closeModal); $('#search').addEventListener('input', renderContents);
document.addEventListener('click', e => { if (e.target.matches('.platform-option')) { e.target.classList.toggle('selected'); const platform = e.target.dataset.platform; selectedPublishPlatforms = e.target.classList.contains('selected') ? [...selectedPublishPlatforms, platform] : selectedPublishPlatforms.filter(item => item !== platform); renderAccountPicker(); } });
document.addEventListener('click', async e => { const login = e.target.closest('.login-account'); if (login) { await window.autopost.loginAccount(login.dataset.accountId); state.activeAccountId = login.dataset.accountId; const account = state.accounts.find(a => a.id === login.dataset.accountId); if (account) account.status = '登录中'; renderAccounts(); return; } const check = e.target.closest('.check-account'); if (check) { check.textContent = '检测中'; const result = await window.autopost.checkAccountLogin(check.dataset.accountId); const account = state.accounts.find(a => a.id === check.dataset.accountId); if (account) account.status = result.status; renderAccounts(); return; } const open = e.target.closest('.open-account'); if (open) { const updated = await window.autopost.openAccountCache(open.dataset.accountId); state.activeAccountId = updated.id; state.accounts = state.accounts.map(a => a.id === updated.id ? updated : a); renderAccounts(); return; } const choose = e.target.closest('.choose-account'); if (choose) { const directory = await window.autopost.chooseDirectory(); if (!directory) return; const updated = await window.autopost.setAccountCacheDir(choose.dataset.accountId, directory); state.accounts = state.accounts.map(a => a.id === updated.id ? updated : a); renderAccounts(); } });
$('#choose-cache-root').addEventListener('click', async () => { const directory = await window.autopost.chooseDirectory(); if (!directory) return; state.settings = await window.autopost.setCacheRoot(directory); $('#cache-root').value = directory; });
$('#new-account').addEventListener('click', () => $('#account-modal').classList.remove('hidden')); $('#close-account-modal').addEventListener('click', () => $('#account-modal').classList.add('hidden')); $('#cancel-account-modal').addEventListener('click', () => $('#account-modal').classList.add('hidden'));
$('#account-form input[name="proxyEnabled"]').addEventListener('change', e => $('#proxy-fields').classList.toggle('hidden', !e.target.checked));
$('#account-form').addEventListener('submit', async e => { e.preventDefault(); const form = new FormData(e.target); const account = await window.autopost.addAccount({ platform: form.get('platform'), name: form.get('name'), note: form.get('note'), proxy: { enabled: form.get('proxyEnabled') === 'on', server: form.get('proxyServer'), username: form.get('proxyUsername'), password: form.get('proxyPassword') } }); state.accounts.push(account); $('#account-modal').classList.add('hidden'); $('#proxy-fields').classList.add('hidden'); e.target.reset(); renderAccounts(); });
$('#content-form').addEventListener('submit', async e => { e.preventDefault(); const form = new FormData(e.target); const selected = [...document.querySelectorAll('.platform-option.selected')].map(el => el.dataset.platform); const targets = [...document.querySelectorAll('.account-option input:checked')].map(input => ({ platform: input.dataset.targetPlatform, accountId: input.dataset.accountId })); if (!selected.length || !targets.length) return alert('请选择至少一个平台和对应账号'); const item = { id: crypto.randomUUID(), type: form.get('type'), title: form.get('title'), file: form.get('file'), body: form.get('body'), tags: form.get('tags'), platforms: selected, targets, createdAt: new Date().toISOString() }; state.contents.unshift(item); state.jobs.unshift({ id: item.id, title: item.title, platforms: selected, targets, status: 'ready' }); await save(); closeModal(); render(); });
boot();
